### PR TITLE
Please comment on my takeaway, GitHub as a social coding tool

### PR DESCRIPTION
**Pull request by YukieTadokoro**
@Pomar , @yurocoro , @ankim16, and Dustin 
I need your feedback on my takeaway and :+1:

### CODE REVIEW

**Comment by YukieTadokoro** [comment]
And @dustinblank , please give me your feedback!

**Comment by ankim16** [comment]
good take away Yukie!

**Comment by Pomar** [comment]
GitHub a great tool for sure and you are experiencing it!

**Comment by yurocoro** [comment]
Great takeaway! GitHub is great tool to take advantage of talents all over the world without meeting in person. (and photo is great too)

**Comment by yurocoro** [comment]
:thumbsup:

**Pull request merged**
