### PR TITLE
Added User_story_matters_when_developing_product

### PR DESCRIPTION
**Pull request by yurocoro**
give me feedback

### CODE REVIEW

**Comment by yurocoro** [comment]
added image.
feedback please:)
@YukieTadokoro
@yurocoro
@dustinblank
@ankim16
@Pomar

**Comment by YukieTadokoro** [comment]
Great takeaway! I'll give you :+1: when you add a link.

**Comment by Pomar** [comment]
Great take away Yuko! In the end, products are built to solve user problems, and if we fail to do that, it is probably just a waste o money.

**Comment by yurocoro** [comment]
Thank you @YukieTadokoro and @Pomar! I added link and additional lines :thumbsup:

**Comment by YukieTadokoro** [comment]
:+1:

**Comment by ankim16** [comment]
Great take away Yuko-San!

**Pull request merged**
