### PR TITLE
Create-managing-without-coding

### PR DESCRIPTION
**Pull request by dustinblank**
@YukieTadokoro @yurocoro @ankim16 @Pomar would love your edits

### CODE REVIEW

**Comment by YukieTadokoro** [comment]
That's a nice takeaway, Dustin! It'll be completed when you add at least one link and one image :smile:

**Comment by ankim16** [comment]
Agreed, good takeaway!

**Comment by yurocoro** [comment]
Great! you should add image too.

**Comment by Pomar** [comment]
Agreed Dustin, I think that it is the the main purpose of this class.

**Pull request merged**
